# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20170721_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
